---

- name: Satellite Register Nodes
  include_tasks: register.yml
  when:
    - sat_register is defined and sat_register|bool == true

- name: Enable Satellite Tools
  include_tasks: sat_tools.yml
  when:
    - sat_tools is defined and sat_tools|bool == true

- name: Satellite Publish CV
  include_tasks: publish.yml
  when:
    - sat_publish is defined and sat_publish|bool == true

- name: Satellite Promote CV
  include_tasks: promote.yml
  when:
    - sat_promote is defined and sat_promote|bool == true

- name: Repo Information
  include_tasks: repos.yml
  when:
    - sat_repos is defined and sat_repos|bool == true



