---
- name: Update Satellite Base Content Views
  shell: "/usr/bin/hammer content-view publish --async --name {{ item }} --organization {{ sat_org }}"
#  delegate_to: "{{ sat_host }}"
  become: true
  with_items: "{{ sat_cv_list }}" 

