version: 2

jobs:
  test:
    machine:
      python:
        version: 2.7.10

    dependencies:
      pre:
        - pip install ansible
    steps:
      - run:
          name: syntax check
          command: ansible-playbook tests/test.yml -i tests/inventory --syntax-check

      - run:
          name: playbook test
          command: |
            ansible-playbook tests/test.yml -i tests/inventory -c local -b
            | grep -q 'changed=0.*failed=0'
            && (echo 'Idempotence test: pass' && exit 0)
            || (echo 'Idempotence test: fail' && exit 1)


